### ISSUE TITLE
Downloads are stucking

### ISSUE THREAD

**Issue by toprak** [asakura42/manyame#7]
The script was giving as ./jg not found because of that I have changed it to jq, it is now working but downloads are stuck, there is no progress.

**Comment by asakura42** [comment]
1) There is no "jg" in the script, maybe you're using wrong one. Try update from repo
2) Downloads may stuck if you have problems with firewall or a releaser's server is down. In 99% it's not the script problem
3) Please attach more information about the problem. Screenshots, videos, logs, etc

**Comment by toprak** [comment]
@asakura42 I meant jq, there are no more information about the problem, it is downloading some part of a file and stuck.
